### ISSUE TITLE
ICNet中特征融合模块

### ISSUE THREAD

**Issue by yangxudong9** [Tramac/awesome-semantic-segmentation-pytorch#102]
你好，在_ICHead中，
    def forward(self, x_sub1, x_sub2, x_sub4):
            outputs = list()
            x_cff_24, x_24_cls = self.cff_24(x_sub4, x_sub2)
            outputs.append(x_24_cls)
            x_cff_12, x_12_cls = self.cff_12(x_sub2, x_sub1)
            outputs.append(x_12_cls)
1/32下采样的特征是不是被丢弃了？
x_cff_12, x_12_cls = self.cff_12(x_cff_24, x_sub1)

**Comment by lxtGH** [comment]
1/32的已经加入到了cff中吧

**Comment by lxtGH** [comment]
https://github.com/lxtGH/Fast_Seg
