### ISSUE TITLE
how can i download the dataset?

### ISSUE THREAD

**Issue by WHUWBS** [Tramac/awesome-semantic-segmentation-pytorch#113]
when i follow the step in readme:
cd ./core/data/downloader
python ade20k.py --download-dir ../datasets/ade
when i run this commad, it can't download the dataset,how should i slove this problem?

**Comment by stormchasingg** [comment]
same problem, just use `python ade20k.py`
it will download the dataset into `~/.torch` folder
create a soft link like `ln -s ~/.torch/path/to/ade ..datasets/ade`

**Comment by WHUWBS** [comment]
it works,thx for your help!

**Comment by XU-GITHUB-curry** [comment]
please what's the meaning of 'create a soft link like ln -s ~/.torch/path/to/ade ..datasets/ade '

**Comment by XU-GITHUB-curry** [comment]
I occured the problem of 'OSError: [Errno 40] Too many levels of symbolic links: '/home/ggw/.torch/datasets/ade/downloads'' when I just use 'python ade20k.py' as the instruction
