### ISSUE TITLE
AssertionError: Please setup the dataset using ../datasets/cityscapes.py

### ISSUE THREAD

**Issue by HITjialanyu** [Tramac/awesome-semantic-segmentation-pytorch#13]
After downloading cityscape dataset and puting it in ../datasets/abe, when runing "python3 train.py --model bisenet --backbone vgg16 --dataset citys --lr 0.0001 --epochs 50",it appears the error.

**Comment by Tramac** [comment]
Hi, Bisenet only suppots resnet18, which is same as paper, please see details in [there](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/master/docs/DETAILS.md).
The [bug](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/issues/9) in downloader has been fixed.

**Comment by HITjialanyu** [comment]
God, I forgot to reply, I am so sorry for this Long-time reply because of test , this is my responsibility.thank you

**Comment by Tramac** [comment]
Never mind!
