### ISSUE TITLE
About the result of cityscape 

### ISSUE THREAD

**Issue by Aktcob** [Tramac/awesome-semantic-segmentation-pytorch#15]
I really care about the result of cityscape dataset. Especially the model Bisenet/ Pspnet. Hope u can release it.

**Comment by Tramac** [comment]
Please give me some time.

**Comment by Aktcob** [comment]
I train bisenet last night. mIoU = 60.9%...orz..

**Comment by Tramac** [comment]
Hi, I am very sorry for the late reply.
It is my responsibility that i have not noted that these [code](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/ea613830b46e07a21c88677d1cecf0c430404fe5/scripts/train.py#L181-183) should be change as:
```
if hasattr(self.model, 'exclusive'):
    for module in self.model.exclusive:
        if module == 'context_path' or module == 'spatial_path':
            params_list.append({'params': getattr(self.model, module).parameters(), 'lr': args.lr})
        else:
            params_list.append({'params': getattr(self.model, module).parameters(), 'lr': args.lr * 10})
```
when config: `crop_size=1024, lr=0.01, epochs=80, use_ohem=True`, mIoU=68.4%, which is still lower than the result in paper, ~74.8%. I will continue to check better parameters or bugs in the code.

**Comment by Aktcob** [comment]
thx... lets fix it~~~

**Comment by Tramac** [comment]
Update: mIoU=70.2% with `aux_loss=True`

**Comment by Aktcob** [comment]
I trained again with the config u mentioned above. mIoU=70.5% with aux.

**Comment by Tramac** [comment]
Good job! However, it is still lower than the result reported in paper, maybe there are better parameters or hidden bugs in code.

**Comment by RAYRAYRAYRita** [comment]
@Aktcob  Hello! I am training bisenet on cityscapes.
May I ask your base-size of cityscapes? If you would be sharing more about your config, I would appreciate it!
