### ISSUE TITLE
I trained the model and I have weights file. But error while evaluating.

### ISSUE THREAD

**Issue by GutlapalliNikhil** [Tramac/awesome-semantic-segmentation-pytorch#154]
Hi people.

I have trained the model and I have weights file. Now I need to evaluate the files. 

I tried the command, "**python eval.py --model fcn32s --backbone vgg16 --dataset sbu**".

Then I got the error like, .

./datasets/shadow/SBU-Test/ShadowImages
Found 4 images in the folder ../datasets/shadow/SBU-Test/ShadowImages
Traceback (most recent call last):
  File "eval.py", line 113, in <module>
    evaluator = Evaluator(args)
  File "eval.py", line 51, in __init__
    norm_layer=BatchNorm2d).to(self.device)
  File "/content/awesome-semantic-segmentation-pytorch/core/models/model_zoo.py", line 122, in get_segmentation_model
    return models[model](**kwargs)
  File "/content/awesome-semantic-segmentation-pytorch/core/models/fcn.py", line 165, in get_fcn32s
    model.load_state_dict(torch.load(get_model_file('fcn32s_%s_%s' % (backbone, acronyms[dataset]), root=root),
KeyError: 'sbu'

I am not able to find how to upload the .PTH file in the eval.py.
Could someone help me in this? Thank you guys.

**Comment by Tramac** [comment]
Please add` 'sbu': 'sbu' `at [here](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/afef72dd6630cd6660d82cbb45beb8e57aa49bf9/core/models/fcn.py#L159).

**Comment by GutlapalliNikhil** [comment]
Thanks @Tramac
