### ISSUE TITLE
The epoch and LR of LIP dataset 

### ISSUE THREAD

**Issue by 853498747** [Tramac/awesome-semantic-segmentation-pytorch#16]
Hi,I found that there are no epoch and LR settings for the LIP dataset in train.py.
Can you give me some suggest?

**Comment by Tramac** [comment]
Hi, maybe `lr=1e-4, epochs=80` is a choice, which reference from [paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Ke_Gong_Instance-level_Human_Parsing_ECCV_2018_paper.pdf).

**Comment by 853498747** [comment]
Hi again<>
What basesize and cropsize can you recommend for LIP datasets? Use deeplabv3 model.
in the dataset Some img size is thin (55*200) ,if shortsize == basesize==520,then h (200)will be convert into 1890,Will crop the easy part and lead to training and testing bad?

**Comment by Tramac** [comment]
Hi, ` crop_size=384` is recommended in [paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Ke_Gong_Instance-level_Human_Parsing_ECCV_2018_paper.pdf), you can set `base_size=420`.
