### ISSUE TITLE
I don't find Fast-SCNN

### ISSUE THREAD

**Issue by jianzhang96** [Tramac/awesome-semantic-segmentation-pytorch#164]
Hello, you list Fast-SCNN in the models, but I don't find it in code. Is Fast-SCNN supported?

**Comment by Tramac** [comment]
hello, plz refer this [repo](https://github.com/Tramac/Fast-SCNN-pytorch).

**Comment by jianzhang96** [comment]
> hello, plz refer this [repo](https://github.com/Tramac/Fast-SCNN-pytorch).

Thanks!
