### ISSUE TITLE
set up error

### ISSUE THREAD

**Issue by onionysy** [Tramac/awesome-semantic-segmentation-pytorch#165]
`ysy@ubuntu:~/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn$ python setup.py build develop
running build
running build_ext
building '._C' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc -I/home/ysy/.local/lib/python2.7/site-packages/torch/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/TH -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/include/python2.7 -c /home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/vision.cpp -o build/temp.linux-x86_64-2.7/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc -I/home/ysy/.local/lib/python2.7/site-packages/torch/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/TH -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/include/python2.7 -c /home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/syncbn_cpu.cpp -o build/temp.linux-x86_64-2.7/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/syncbn_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc -I/home/ysy/.local/lib/python2.7/site-packages/torch/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/TH -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/include/python2.7 -c /home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/psa_cpu.cpp -o build/temp.linux-x86_64-2.7/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/psa_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc -I/home/ysy/.local/lib/python2.7/site-packages/torch/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/TH -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/include/python2.7 -c /home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/ca_cpu.cpp -o build/temp.linux-x86_64-2.7/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cpu/ca_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-10.0/bin/nvcc -DWITH_CUDA -I/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc -I/home/ysy/.local/lib/python2.7/site-packages/torch/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/TH -I/home/ysy/.local/lib/python2.7/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/include/python2.7 -c /home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cuda/syncbn_cuda.cu -o build/temp.linux-x86_64-2.7/home/ysy/lane_test/awesome-semantic-segmentation-pytorch-master/core/nn/csrc/cuda/syncbn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -std=c++11
unable to execute u':/usr/local/cuda-10.0/bin/nvcc': No such file or directory
error: command u':/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1
`

my ~/.bashrc
`

export PATH="/usr/local/cuda-10.0/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ysy/3rdparty/TensorRT-6.0.1.5/lib
export PATH="$PATH:/home/ysy/3rdparty/TensorRT-6.0.1.5"

source /opt/ros/kinetic/setup.bash --extend

source ~/catkin/tele15-ros/devel/setup.bash --extend

source ~/catkin/LeGO-LOAM/devel/setup.bash --extend
source ~/catkin/LOAM_livox/devel/setup.bash --extend
source ~/catkin/LOAM/devel/setup.bash --extend

source ~/catkin/robot_pose_ekf/devel/setup.bash --extend
`

I don not know how to fix it. Can you give me some advices? thank you very much.

**Comment by Tramac** [comment]
`/usr/local/cuda-10.0/bin/nvcc': No such file or directory error`.
Maybe cuda is not installed correctly？

**Comment by onionysy** [comment]
![图片](https://user-images.githubusercontent.com/55376216/100984794-21916a80-3586-11eb-81ee-b8ecf50c319d.png)

**Comment by onionysy** [comment]
> `/usr/local/cuda-10.0/bin/nvcc': No such file or directory error`.
> Maybe cuda is not installed correctly？

but the nvcc is in the file. And I can use cuda train other models.

**Comment by Tramac** [comment]
What is the pytorch version？

**Comment by onionysy** [comment]
> What is the pytorch version？

pytorch 1.40
