### ISSUE TITLE
window or ubuntu?在win10上面编译有错误：\THCNumerics.cuh(175): error: more than one operator "<" matches these operands:

### ISSUE THREAD

**Issue by machine52vision** [Tramac/awesome-semantic-segmentation-pytorch#17]
你好，请问项目是在window or ubuntu系统?在win10上面编译有错误：\THCNumerics.cuh(175): error: more than one operator "<" matches these operands:

**Comment by Tramac** [comment]
你好，项目是在ubuntu16.04下完成，可以给出具体的错误日志么？

**Comment by machine52vision** [comment]
D:/software/install/anaconda/lib/site-packages/torch/lib/include/TH\THAllocator.h(77): warning: field of class type without a DLL interface used in a class with a DLL interface

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCAllocator.h(15): warning: field of class type without a DLL interface used in a class with a DLL interface

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(175): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: c10::Half < c10::Half

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(176): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: c10::Half <= c10::Half

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(177): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: c10::Half > c10::Half

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(178): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: c10::Half >= c10::Half

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(179): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half

d:\software\install\anaconda\lib\site-packages\torch\lib\include\thc\THCNumerics.cuh(180): error: more than one operator "!=" matches these operands:
            built-in operator "arithmetic != arithmetic"
            function "operator!=(const __half &, const __half &)"
            operand types are: c10::Half != c10::Half

6 errors detected in the compilation of "C:/Users/machi/AppData/Local/Temp/tmpxft_000031e4_00000000-8_ca_cuda.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2

**Comment by Tramac** [comment]
Try to remove code `#include <THC/THCAtomics.cuh>` in [ca_cuda.cu](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/226cb391628405fec1d0dc1ac075c65381d5fda1/core/nn/csrc/cuda/ca_cuda.cu#L5) and [psa_cuda](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/226cb391628405fec1d0dc1ac075c65381d5fda1/core/nn/csrc/cuda/psa_cuda.cu#L5).

**Comment by machine52vision** [comment]
thanks a lot!

**Comment by Tramac** [comment]
Is the bug solved?
