### ISSUE TITLE
Storage has wong size

### ISSUE THREAD

**Issue by liu-zg15** [Tramac/awesome-semantic-segmentation-pytorch#170]
Thank you for your repo.
I trained a fcn_resnet50 with 2GPUS.
Batch size is 8.
When I want to eval the model. I used the eval(ditributed).
But get RunTimeERROR: storage has wrong size: expected -4807629896541614912 got 262144.
Why this happened?
and how to solve it?
@Tramac @roclark @liminn @MaKaNu

**Comment by Tramac** [comment]
Hi, maybe the batch is too large to OOM.
