### ISSUE TITLE
cannot import name '_C' from partially initialized module 'core.nn' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ggohem** [Tramac/awesome-semantic-segmentation-pytorch#175]
Hi，guys, I encountered the following error when running the code:

ImportError: cannot import name '_C' from partially initialized module 'core.nn' (most likely due to a circular import) (/backup/mingjin/pycharm/Exercise/semantic_segmentation/core/nn/__init__.py)

My training parameters are as follows：
--model bisenet --backbone resnet18 --dataset pascal_voc --lr 0.0001 --epochs 50

What should I do？Please help me，Thx！

**Comment by Tramac** [comment]
Hi, please run `python setup.py build develop` first.
