### ISSUE TITLE
Problem for importing _C

### ISSUE THREAD

**Issue by scey26** [Tramac/awesome-semantic-segmentation-pytorch#176]
My error message is as below:
_"_c.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _zn2at19undefinedtensorimpl10_singletone"_

Maybe, i don't need to care about __C_ when i'm not gonna use the model 'CCNet', Right?

**Comment by Tramac** [comment]
You are right, only CCNet and EncNet depend on _C.

**Comment by scey26** [comment]
Thanks for your fast reply!

First of all, i ran "python setup.py build develop first". But, the error message is same as above.

Through googling, i found some solutions which others works.

1. Checking "import torch" before "import _C"
2. trying "rm -rf build" before running train.py

However, i failed all cases. If you are familiar with process of importing _C, could you help me?
(actually, i'm guessing "python setup.py build develop" is doesn't work for my PC..)

**Comment by Tramac** [comment]
PyTorch=1.1.0 and CUDA=8.0 is ok for my linux. Maybe you can try to remove the code related to _C if you don't care CCNet, such as [ca_block.py](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/master/core/nn/ca_block.py).

**Comment by scey26** [comment]
Ok! Really appreciate it
