### ISSUE TITLE
Can you leave a message to tell me what improvements your project has made compared with icnet?

### ISSUE THREAD

**Issue by CopenhagenDazs** [Tramac/awesome-semantic-segmentation-pytorch#178]
i am a Hunan University bachelor,Can you leave a message to tell me what improvements your project has made compared with icnet? Thank you very much！

**Comment by CopenhagenDazs** [comment]
I am writing my graduation thesis. I have run your project successfully, but I still don't understand the principle. Please answer my question.Thx:）

**Comment by Tramac** [comment]
Hello, maybe you need to read the [paper](https://arxiv.org/pdf/1704.08545.pdf) for more details.

**Comment by CopenhagenDazs** [comment]
I get it,thanks!
