### ISSUE TITLE
为什么在用dfaNet的时候报错

### ISSUE THREAD

**Issue by dengyufuqin** [Tramac/awesome-semantic-segmentation-pytorch#183]
one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 8, 256, 256]], which is output 0 of ReluBackward1, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by wzr0108** [comment]
请问解决了吗
