### ISSUE TITLE
Missing key problem

### ISSUE THREAD

**Issue by y1225007** [Tramac/awesome-semantic-segmentation-pytorch#20]
Hi,thanks for your code. But there are some missing key errors when I try to train danet . I really don't know how to solve it. 
![47411597-9058-499C-9524-6686DB698D25](https://user-images.githubusercontent.com/15275241/58753242-c4c77680-84ee-11e9-8684-fdd7cc368df0.png)

**Comment by tanghf27** [comment]
> Hi,thanks for your code. But there are some missing key errors when I try to train danet . I really don't know how to solve it.
> ![47411597-9058-499C-9524-6686DB698D25](https://user-images.githubusercontent.com/15275241/58753242-c4c77680-84ee-11e9-8684-fdd7cc368df0.png)

Did you solve it?
