### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by wangxin1233** [Tramac/awesome-semantic-segmentation-pytorch#21]
thank you for your code. could you tell me what the mean of this code:
cd awesome-semantic-segmentation-pytorch/core/nn
python setup.py build develop.
and the error is occur when i run it, could you help me how  to solve it?
![1111](https://user-images.githubusercontent.com/44840625/58806739-64008100-8649-11e9-9a91-23aef3eb0c91.png)

**Comment by Tramac** [comment]
Hi, this code builds for `syncbn`, `CCNet` and `PSANet`.
Please update pytorch to version 1.1.

**Comment by wangxin1233** [comment]
ok  thank you

**Comment by Tramac** [comment]
Is it solved?

**Comment by wangxin1233** [comment]
thank you  it solved. pytorch ==1.1.0
but when i run ,python train.py --model fcn32s --backbone vgg16 --dataset pascal_voc --lr 0.0001 --epochs 50
the error is :
![图片](https://user-images.githubusercontent.com/44840625/58847493-c2634900-86b5-11e9-8bca-650911d56f38.png)
I referred to the following problem but did not solve it
![图片](https://user-images.githubusercontent.com/44840625/58847596-21c15900-86b6-11e9-923d-c7b768d0157b.png)
hope your answers,thank you very much

**Comment by Tramac** [comment]
Do you run `python setup.py build develop` successfully?

**Comment by wangxin1233** [comment]
yes,successfully!
![图片](https://user-images.githubusercontent.com/44840625/58847921-289c9b80-86b7-11e9-80c0-b8748d1576f3.png)
and I found that there isn't  the file _c.py
![图片](https://user-images.githubusercontent.com/44840625/58847994-71eceb00-86b7-11e9-8f37-7171abe8c1cb.png)

**Comment by Tramac** [comment]
It is in `/home/wx/.local/share/Trash/files/core/nn`.

**Comment by wangxin1233** [comment]
I didn't change any path

**Comment by wangxin1233** [comment]
when i run python setup.py build develop,the error is   Permission denied, so I add sudo , is this reason?

**Comment by Tramac** [comment]
Please try to delete the previous `_C` file and recompile it.

**Comment by wangxin1233** [comment]
I delete all the file and upload again,then I run the   sudo  python setup.py ,but it wrong again.I don't know where it caused. thank you for your help!
![图片](https://user-images.githubusercontent.com/44840625/58851484-846e2100-86c5-11e9-8593-f69a58eb90d3.png)
![图片](https://user-images.githubusercontent.com/44840625/58851509-95b72d80-86c5-11e9-84f4-8b7bb6a21919.png)
 thank you very much

**Comment by wangxin1233** [comment]
I have solved! thank you very much!

**Comment by Tramac** [comment]
Great!

**Comment by Tramac** [comment]
@wangxin1233 Hi, what is the reason of this bug?

**Comment by wangxin1233** [comment]
when i run this code ,add sudo and solved!
