### ISSUE TITLE
python setup.py error

### ISSUE THREAD

**Issue by 82018303kazuma** [Tramac/awesome-semantic-segmentation-pytorch#23]
python setup.py build develop（pytorch ==1.1.0）

2 errors detected in the compilation of "/tmp/tmpxft_000015ae_00000000-7_psa_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

I can not setup.
I saw ”error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 #21” but I could not solve it

**Comment by Tramac** [comment]
@wangxin1233 
Hi, can you give some advice?

**Comment by 82018303kazuma** [comment]
I have no advice.　sorry.

**Comment by Tramac** [comment]
en, i was asking @wangxin1233 for advice.

**Comment by 82018303kazuma** [comment]
What is the version of cuda?

**Comment by Tramac** [comment]
The project was tested on CUDA8.0 and CUDA10.0.

**Comment by 82018303kazuma** [comment]
I thought that CUDA 8.0 was the cause, but it is not.

**Comment by Tramac** [comment]
Can you provide the detail bugs info?

**Comment by 82018303kazuma** [comment]
python setup.py build develop

error
ーーーーーーーーーーーーーーー
running build
running build_ext
building '._C' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/atsushi
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu
creating build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cuda
gcc -pthread -B /home/atsushi/.pyenv/versions/anaconda3-5.0.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/TH -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/include/python3.6m -c /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/atsushi/.pyenv/versions/anaconda3-5.0.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/TH -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/include/python3.6m -c /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/syncbn_cpu.cpp -o build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/syncbn_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/atsushi/.pyenv/versions/anaconda3-5.0.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/TH -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/include/python3.6m -c /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.cpp -o build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/atsushi/.pyenv/versions/anaconda3-5.0.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/TH -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/include/python3.6m -c /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.cpp -o build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/TH -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/atsushi/.pyenv/versions/anaconda3-5.0.1/include/python3.6m -c /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cuda/psa_cuda.cu -o build/temp.linux-x86_64-3.6/home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn/csrc/cuda/psa_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/c10/util/Half-inl.h(21): error: identifier "__half_as_short" is undefined

/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/atsushi/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/include/THC/THCNumerics.cuh(195): error: identifier "__half_as_ushort" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000021af_00000000-7_psa_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
ーーーーーーーーーーーーーーー

**Comment by Tramac** [comment]
Maybe it need to update CUDA, but i'm not sure.

**Comment by 82018303kazuma** [comment]
pytorch in python 3.6.8 feels good cuda 9.0 or more.

**Comment by 82018303kazuma** [comment]
Installed /home/atsushi/Pytorch/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

I have solved! thank you very much!

It also depends on the python version, but as expected cuda 8.0 was the cause.

**Comment by Tramac** [comment]
Great!
