### ISSUE TITLE
error when running demo.py with pascal voc 2012

### ISSUE THREAD

**Issue by ximitiejiang** [Tramac/awesome-semantic-segmentation-pytorch#24]
python3 ex_demo.py --model fcn32s_vgg16_voc
Traceback (most recent call last):
  File "ex_demo.py", line 12, in <module>
    from core.utils.visualize import get_color_pallete
  File "/home/ubuntu/suliang_git/awesome-semantic-segmentation-pytorch/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/home/ubuntu/suliang_git/awesome-semantic-segmentation-pytorch/core/nn/__init__.py", line 4, in <module>
    from .ca_block import *
  File "/home/ubuntu/suliang_git/awesome-semantic-segmentation-pytorch/core/nn/ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: /home/ubuntu/suliang_git/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

hello, when i run demo.py, above error occured.  seems related to compile, but i have run the setup.py successfully. my pytorch version is 1.01, cuda9.0, could you suggest what can i do next to fix it?

thanks

**Comment by Tramac** [comment]
Hi, please update pytorch to verson 1.1.

**Comment by ximitiejiang** [comment]
i update pytorch to 1.1, and recompile again, but the problem still happen. 
then i tried to delete the _C.cython-37m-x86_64-linux-gnu.so and recompile, but no use.

my pytorch1.1 & torchvision3.0 &cudatoolkit9.0 are all installed in conda virtual enviroment.

**Comment by Tramac** [comment]
You can try to update python version to 3.7.

**Comment by ximitiejiang** [comment]
still not help...

**Comment by ximitiejiang** [comment]
solved.
rm -r build, then recompile.
refer to: https://github.com/facebookresearch/maskrcnn-benchmark/issues/421, which is using similiar setup.py.
