### ISSUE TITLE
how to download pretrained models

### ISSUE THREAD

**Issue by Markovcom** [Tramac/awesome-semantic-segmentation-pytorch#27]

**Comment by Tramac** [comment]
It will download pretrained model automatically.

**Comment by Markovcom** [comment]
@Tramac sorry, i say the pretrainded model not pretrained base models.
![image](https://user-images.githubusercontent.com/26458922/59266641-af82e280-8c7a-11e9-8075-f1c5d151ab16.png)
i run the demo.py, meet this.

**Comment by Tramac** [comment]
Please change [root](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/9c37f7ca1fd051090469e378e256c19d19ae1eb4/core/models/fcn.py#L151) parameter to the path to trained model saved.

**Comment by Markovcom** [comment]
thank you.

**Comment by jiaobingle** [comment]
when i run 'python train.py --model icnet --backbone resnet50 --dataset pascal_voc --lr 0.0001 --epochs 50', it shows
……
Model file /root/.torch/models/resnet50-25c4b509.pth is not found. Downloading.
Downloading /root/.torch/models/resnet50-25c4b509.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet50-25c4b509.zip
……

but, i have modified the 'root' as mentioned above 'get_icnet() in icnet.py', so how can i solve it, thx!
