### ISSUE TITLE
cannot import name '_C'

### ISSUE THREAD

**Issue by shuaizzZ** [Tramac/awesome-semantic-segmentation-pytorch#36]
from core.nn import _C

ImportError: cannot import name '_C'

**Comment by alex337** [comment]
hey,how do you solve the problem,

**Comment by shuaizzZ** [comment]
Still have not solved this problem

**Comment by alex337** [comment]
感觉是版本的原因？




------------------ 原始邮件 ------------------
发件人: "shuaizzZ"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 晚上7:27
收件人: "Tramac/awesome-semantic-segmentation-pytorch"<awesome-semantic-segmentation-pytorch@noreply.github.com>;
抄送: "1964840264"<1964840264@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Tramac/awesome-semantic-segmentation-pytorch] cannot import name'_C' (#36)




Still have not solved this problem

**Comment by shuaizzZ** [comment]
不晓得哎，我是pytorch1.0.1.post2，你呢？

**Comment by Tramac** [comment]
Please run ‘python setup.py build develop’.

**Comment by Tramac** [comment]
Please run ‘python setup.py build develop’.

**Comment by alex337** [comment]
> 不晓得哎，我是pytorch1.0.1.post2，你呢？
他说的好像可以了，老哥你是哪个学校的

**Comment by alex337** [comment]
> Please run ‘python setup.py build develop’.

thanks!

**Comment by kame-hameha** [comment]
Hello, I have the same problem:
- Ubuntu 18.04
- CUDA10.0
- I use NVIDIA Docker: 2.0.3: https://github.com/anibali/docker-pytorch
 
I ran 'python setup.py build develop' and get the following output outside the docker:
########################################
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda/'
running build
running build_ext
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing top-level names to semantic_segmentation.egg-info/top_level.txt
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/_C.so -> 
Creating /usr/local/lib/python2.7/dist-packages/semantic-segmentation.egg-link (link to .)
semantic-segmentation 0.1 is already the active version in easy-install.pth

Installed /home/kame/git/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1
########################################
--> Is the egg-link in python2.7 correct or should it be python3.6?

--> Running the training script  'python train.py --model fcn32s --backbone vgg16 --dataset pascal_voc --lr 0.0001 --epochs 50' gives me some errors that I do not understand:
########################################
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "/mnt/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/mnt/core/nn/__init__.py", line 4, in <module>
    from .ca_block import *
  File "/mnt/core/nn/ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: /mnt/core/nn/_C.so: undefined symbol: _Py_ZeroStruct
########################################

I am glad for any help or suggestions!

PS: the docker container works perfectly with your Fast-SCNN implementation: 'https://github.com/Tramac/Fast-SCNN-pytorch#datasets' - not sure what I am doing wrong...

**Comment by kame-hameha** [comment]
Just ran 'python3 setup.py build develop' because I have python2.7 and 3.6 installed. Works fine now:
###########################
running build
running build_ext
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so -> 
Creating /usr/local/lib/python3.6/dist-packages/semantic-segmentation.egg-link (link to .)
semantic-segmentation 0.1 is already the active version in easy-install.pth

Installed /home/kame/git/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1
###########################
Except the other train/demo/... scripts which output e.g. for the 'demo.py':

python scripts/demo.py --model fcn32s_vgg16_voc --input-pic
###########################
Traceback (most recent call last):
  File "scripts/demo.py", line 12, in <module>
    from core.utils.visualize import get_color_pallete
  File "/mnt/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/mnt/core/nn/__init__.py", line 4, in <module>
    from .ca_block import *
  File "/mnt/core/nn/ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: /mnt/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE
###########################

**Comment by anqin5211314** [comment]
我也遇到这个问题了  请问你们解决了吗？

**Comment by anqin5211314** [comment]
我运行了 ‘python setup.py build develop’.  但是 还是报错

**Comment by anqin5211314** [comment]
gcc -pthread -B /home/anqin/anaconda3/envs/VSR/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/TH -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/THC -I:/usr/local/cuda-10.0/include -I/home/anqin/anaconda3/envs/VSR/include/python3.6m -c /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.cpp -o build/temp.linux-x86_64-3.6/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

运行 “python setup.py build develop“ 以后的log 代码主 这个有什么问题吗？

**Comment by anqin5211314** [comment]
gcc -pthread -B /home/anqin/anaconda3/envs/VSR/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/TH -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/THC -I:/usr/local/cuda-10.0/include -I/home/anqin/anaconda3/envs/VSR/include/python3.6m -c /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.cpp -o build/temp.linux-x86_64-3.6/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-10.0/bin/nvcc -DWITH_CUDA -I/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/TH -I/home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/torch/lib/include/THC -I:/usr/local/cuda-10.0/include -I/home/anqin/anaconda3/envs/VSR/include/python3.6m -c /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cuda/ca_cuda.cu -o build/temp.linux-x86_64-3.6/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/csrc/cuda/ca_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-10.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1

**Comment by anqin5211314** [comment]
以上问题解决 但是出现了新的问题：
ImportError: /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
下边是完整的log

(VSR) anqin@anqin-N85-87HP6:~/ICnet/awesome-semantic-segmentation-pytorch/scripts$ python eval.py --model fcn32s --backbone vgg16 --dataset pascal_voc
Traceback (most recent call last):
  File "eval.py", line 15, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/__init__.py", line 4, in <module>
    from .ca_block import *
  File "/home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by anqin5211314** [comment]
新的问题：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 3: invalid start byte
如何解决？

**Comment by anqin5211314** [comment]
执行python setup.py build develop  出现以下log 是成功了吗？
(VSR) anqin@anqin-N85-87HP6:~/ICnet/awesome-semantic-segmentation-pytorch/core/nn$ python setup.py build develop
running build
running build_ext
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so -> 
Creating /home/anqin/anaconda3/envs/VSR/lib/python3.6/site-packages/semantic-segmentation.egg-link (link to .)
semantic-segmentation 0.1 is already the active version in easy-install.pth

Installed /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

**Comment by anqin5211314** [comment]
求助求助求助 
from core.nn import _C
ImportError: /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
怎么解决？

**Comment by Tramac** [comment]
Which the pytorch version?

**Comment by anqin5211314** [comment]
pytorch viersion == 1.1.0

**Comment by anqin5211314** [comment]
python v == 3.6 
torchvision == 0.3.0

**Comment by anqin5211314** [comment]
I have reinstall my torch again and again ,but don't resolve the problem

**Comment by Tramac** [comment]
Can it be compiled successfully?

**Comment by anqin5211314** [comment]
I show you compiled log wait

**Comment by anqin5211314** [comment]
(ICnet) anqin@anqin-N85-87HP6:~/ICnet/awesome-semantic-segmentation-pytorch/core/nn$ python setup.py build develop
running build
running build_ext
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so -> 
Creating /home/anqin/anaconda3/envs/ICnet/lib/python3.6/site-packages/semantic-segmentation.egg-link (link to .)
Adding semantic-segmentation 0.1 to easy-install.pth file

Installed /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

**Comment by anqin5211314** [comment]
can we add wechat ? I real need U help .

**Comment by Tramac** [comment]
Give me your WeChat.

**Comment by anqin5211314** [comment]
17824843313 sososo thanks

**Comment by anqin5211314** [comment]
17824853313

**Comment by anqin5211314** [comment]
thanks sososososo much

**Comment by Dorispaopao** [comment]
I can't find out the setup.py , and how do you deal with this problem?

**Comment by cqwwww** [comment]
Does anyone solve this problem? I have met the same problem...

**Comment by vikiQiu** [comment]
> Give me your WeChat.

I have the same problem after successfully build develop the setup.py file...
My pytorch version is 1.1.0 cuda 9.0 python 3.5
Can I add your wechat too？

**Comment by Tramac** [comment]
> > Give me your WeChat.
> 
> I have the same problem after successfully build develop the setup.py file...
> My pytorch version is 1.1.0 cuda 9.0 python 3.5
> Can I add your wechat too？

Uh...please give me your WeChat.

**Comment by vikiQiu** [comment]
> > > Give me your WeChat.
> > 
> > 
> > I have the same problem after successfully build develop the setup.py file...
> > My pytorch version is 1.1.0 cuda 9.0 python 3.5
> > Can I add your wechat too？
> 
> Uh...please give me your WeChat.

I run the `python setup.py build develop` twice and then solve this problem. I don't know why the first time it successfully installed it does not works... weird...
Thanks a lot!

**Comment by Dorispaopao** [comment]
whose wechat?






At 2019-08-02 14:42:10, "Tramac" <notifications@github.com> wrote:


Give me your WeChat.

I have the same problem after successfully build develop the setup.py file...
My pytorch version is 1.1.0 cuda 9.0 python 3.5
Can I add your wechat too？

Uh...please give me your WeChat.

**Comment by Dorispaopao** [comment]
Did you do this operation?






At 2019-08-02 14:32:38, "vikiQiu" <notifications@github.com> wrote:


Give me your WeChat.

I have the same problem after successfully build develop the setup.py file...
My pytorch version is 1.1.0 cuda 9.0 python 3.5
Can I add your wechat too？

**Comment by Dorispaopao** [comment]
Did you do this operation?



cd awesome-semantic-segmentation-pytorch/core/nn
python setup.py build develop



At 2019-08-02 14:32:38, "vikiQiu" <notifications@github.com> wrote:


Give me your WeChat.

I have the same problem after successfully build develop the setup.py file...
My pytorch version is 1.1.0 cuda 9.0 python 3.5
Can I add your wechat too？

**Comment by Tramac** [comment]
Please post your bug log.

**Comment by mozhuqing** [comment]
> Please run ‘python setup.py build develop’.
No setup.py was found.

**Comment by genghuan2005** [comment]
> from core.nn import _C
> 
> ImportError: cannot import name '_C'

did not solve this problem? I have run 'python setup.py build develop' and there exists many warnings,the logs is:
running build
running build_ext
/home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
/home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so -> 
Creating /home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/semantic-segmentation.egg-link (link to .)
semantic-segmentation 0.1 is already the active version in easy-install.pth

Installed /home/import/gh/Segmt/awesome-semantic-segmentation-pytorch-master/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

**Comment by Dorispaopao** [comment]
Yeah, I just did the "import" operation. Maybe you are missing some necessary libraries```






At 2019-08-21 16:32:40, "genghuan2005" <notifications@github.com> wrote:


from core.nn import _C

ImportError: cannot import name '_C'

did not solve this problem? I have run 'python setup.py build develop' and there exists many warnings,the logs is:
running build
running build_ext
/home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning:

                           !! WARNING !!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                          !! WARNING !!


warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
running develop
running egg_info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
/home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning:

                           !! WARNING !!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                          !! WARNING !!


warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so ->
Creating /home/import/anaconda3/envs/pytorch1_1/lib/python3.6/site-packages/semantic-segmentation.egg-link (link to .)
semantic-segmentation 0.1 is already the active version in easy-install.pth

Installed /home/import/gh/Segmt/awesome-semantic-segmentation-pytorch-master/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

**Comment by baibaidj** [comment]
I'm using Mac without GPU and encountered this issue also. 
As the warning suggested, I tried to upgrade the GCC with 
`brew upgrade gcc`
BUT, still failed. After some search, I solved the problem using the following command. 
`CFLAGS='-stdlib=libc++' python setup.py build develop`
Hopes it working for you.

**Comment by nanian111** [comment]
can we add wechat ? I real need U help . @shuaizzZ  @anqin5211314  I have met the same problem

**Comment by renmmmmmm** [comment]
creating C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\build\lib.win-amd64-3.6
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\Anaconda3\envs\awesome\lib\site-packages\torch\lib /LIBPATH:E:\Anaconda3\envs\awesome\libs /LIBPATH:E:\Anaconda3\envs\awesome\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" c10.lib torch.lib torch_python.lib _C.lib /EXPORT:PyInit__C build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\vision.obj build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\cpu\ca_cpu.obj build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\cpu\psa_cpu.obj build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\cpu\syncbn_cpu.obj /OUT:build\lib.win-amd64-3.6\_C.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\_C.cp36-win_amd64.lib
  正在创建库 build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\_C.cp36-win_amd64.lib 和对象 build\temp.win-amd64-3.6\Release\awesome-semantic-segmentation-pytorch-master\core\nn\csrc\_C.cp36-win_amd64.exp
正在生成代码
已完成代码的生成
running develop
running egg_info
creating semantic_segmentation.egg-info
writing semantic_segmentation.egg-info\PKG-INFO
writing dependency_links to semantic_segmentation.egg-info\dependency_links.txt
writing top-level names to semantic_segmentation.egg-info\top_level.txt
writing manifest file 'semantic_segmentation.egg-info\SOURCES.txt'
reading manifest file 'semantic_segmentation.egg-info\SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info\SOURCES.txt'
running build_ext
copying build\lib.win-amd64-3.6\_C.cp36-win_amd64.pyd ->
Creating e:\anaconda3\envs\awesome\lib\site-packages\semantic-segmentation.egg-link (link to .)
Adding semantic-segmentation 0.1 to easy-install.pth file

Installed c:\program files (x86)\microsoft visual studio\2017\enterprise
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1

(awesome) C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>python D:\awesome-semantic-segmentation-pytorch-master\scripts\train.py --model deeplabv3 --backbone resnst50 --dataset citys --lr 0.0001 --epochs 50
Traceback (most recent call last):
  File "D:\awesome-semantic-segmentation-pytorch-master\scripts\train.py", line 18, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "D:\awesome-semantic-segmentation-pytorch-master\core\__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "D:\awesome-semantic-segmentation-pytorch-master\core\nn\__init__.py", line 4, in <module>
    from .ca_block import *
  File "D:\awesome-semantic-segmentation-pytorch-master\core\nn\ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: cannot import name '_C'
编译成功了为什么还会报这个错？？

**Comment by renmmmmmm** [comment]
> Can it be compiled successfully?

版本兼容是什么意思啊？pytorch=1.2 Python=3.6 cuda=10.0 torchvision=0.4

**Comment by alex337** [comment]
> 求助求助求助
> from core.nn import _C
> ImportError: /home/anqin/ICnet/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
> 怎么解决？

老哥解决了吗

**Comment by alex337** [comment]
> Please post your bug log.

ImportError: /public/home/yujz/env_file/tools/cuda/semantic-segmentation/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
hi,i have met the same problem,how can i solve the problem

**Comment by keepgoing365** [comment]
> Please run ‘python setup.py build develop’.
Dear Tramac，Are you using Linux system? I use Windows10 to configure,then there are so many errors! Could u please help me? my wechat is 15228961174.Thank u very much!

**Comment by keepgoing365** [comment]
> Please post your bug log.

Dear Tramac，Are you using Linux system? I use Windows10 to configure,then there are so many errors! Could u please help me? my wechat is 15228961174.Thank u very much!

**Comment by azulgranakun** [comment]
my wechat is 849072785，please！！！

**Comment by Tramac** [comment]
> my wechat is 849072785，please！！！

done.

**Comment by weTerence** [comment]
> > my wechat is 849072785，please！！！
> 
> done.

ImportError: /home2/HWGroup/jinjh/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
Hi, I have met the same problem, how can solve it. My wehcat is jjhboss. I'd be very grateful if you help me!
