### ISSUE TITLE
How should I set one particular GPU in your train.py code?

### ISSUE THREAD

**Issue by just-blank** [Tramac/awesome-semantic-segmentation-pytorch#42]
Hello, thanks for your great job!
I came up a problem when I try to set GPU in single GPU training. I can not figure out how you set
 up the GPU through the arguments. For example, I have four GPUs in my server, I only want to use the second GPU，how should I set  the arguments or change some codes in your train.py code?

**Comment by Tramac** [comment]
Hi, please add `CUDA_VISIBLE_DEVICES=0(your GPU)` before train.
