### ISSUE TITLE
load cityscapes dataset

### ISSUE THREAD

**Issue by LYJvincent** [Tramac/awesome-semantic-segmentation-pytorch#52]
1)Could you tell me how to load my dataset to the fast scnn network? 
2) how to use the self._key = np.array([-1, -1, -1, -1, -1, -1,
                              -1, -1, 0, 1, -1, -1,
                              2, 3, 4, -1, -1, -1,
                              5, -1, 6, 7, 8, 9,
                              10, 11, 12, 13, 14, 15,
                              -1, -1, 16, 17, 18]) , the self._key come from the cityscapes.py

**Comment by Tramac** [comment]
1)Please describe your dataset in more detail.
2)The key map is used to correct the index value of cityscapes dataset.

**Comment by LYJvincent** [comment]
Thank you very much for your reply！
 My dataset contains more than two categories ,just like  background and defect.if i use the cityscapes.py
 how should i modify the cityscapes.py or the key map? thank you!!!
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Tramac"<notifications@github.com>;
 发送时间: 2019年7月31日(星期三) 晚上8:15
 收件人: "Tramac/awesome-semantic-segmentation-pytorch"<awesome-semantic-segmentation-pytorch@noreply.github.com>;
 抄送: "沉静的奢华"<781658795@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [Tramac/awesome-semantic-segmentation-pytorch] load cityscapesdataset (#52)

 

 
1)Please describe your dataset in more detail.
2)The key map is used to correct the index value of cityscapes dataset.

**Comment by Tramac** [comment]
Maybe reference `pascal_voc.py` is better.

**Comment by LYJvincent** [comment]
ok. thank you!!!
