### ISSUE TITLE
problem when: python setup.py build develop

### ISSUE THREAD

**Issue by electronicYH** [Tramac/awesome-semantic-segmentation-pytorch#53]
yh@amax:/data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn$ python setup.py build develop
running build
running build_ext
building '._C' extension
gcc -pthread -B /home/yh/.conda/envs/yh/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/home/yh/.conda/envs/yh/lib/python3.6/site-packages/torch/lib/include -I/home/yh/.conda/envs/yh/lib/python3.6/site-packages/torch/lib/include/TH -I/home/yh/.conda/envs/yh/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/yh/.conda/envs/yh/include/python3.6m -c /data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.o -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc/ca.h:3:0,
                 from /data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.cpp:1:
/data/yh/proj/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/vision.h:2:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by electronicYH** [comment]
please help me

**Comment by Tramac** [comment]
Which your Pytorch version?

**Comment by electronicYH** [comment]
python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.4.1'
>>>

**Comment by Tramac** [comment]
Please update Pytorch to version 1.1.
