### ISSUE TITLE
There is an error, when I run the data script, that FileExistsError: [Errno 17] File exists: '../datasets/ade' -> '/home/wyz/.torch/datasets/ade'

### ISSUE THREAD

**Issue by beizhengren** [Tramac/awesome-semantic-segmentation-pytorch#55]
There is an error, when I run the data script, that FileExistsError: [Errno 17] File exists: '../datasets/ade' -> '/home/wyz/.torch/datasets/ade'
![image](https://user-images.githubusercontent.com/22186249/62607317-77bdb180-b930-11e9-8dbe-cabf2e3c08eb.png)
what does it mean, and why?
Thank you!

**Comment by Tramac** [comment]
Please check the `/home/wyz/.torch/datasets/ade`, is there the ADE datasets?

**Comment by beizhengren** [comment]
@Tramac With my own understanding, this script is used to download the datasets. I make a directory "../datasets/ade".That error still existed.
And  '->' means the soft link?
Thank you!

**Comment by HareshMiriyala** [comment]
I resolved this issue by deleting the datasets/ade folder under ~/.torch directory
