### ISSUE TITLE
KeyError: 'local_rank'

### ISSUE THREAD

**Issue by beizhengren** [Tramac/awesome-semantic-segmentation-pytorch#57]
Hi~
When I run the command that  'python demo.py --model fcn32s_vgg16_voc --input-pic ./datasets/test.jpg' , I meet KeyError: 'local_rank' .
What should I do?
Thank you! 

![image](https://user-images.githubusercontent.com/22186249/62674545-6e3a5500-b9d5-11e9-8eba-edf951e47070.png)

**Comment by beizhengren** [comment]
Is there anyone could help me?Thanks a lot!

**Comment by mumuyanyan** [comment]
i also have the problem

TypeError: __init__() got an unexpected keyword argument 'local_rank'

**Comment by gaoyangxixi** [comment]
You can try to delete the keyword

**Comment by sainatarajan** [comment]
Instead of `kwargs['local_rank']` in `eval.py` or `demo.py`, substitute it with 0 or 1 accordingly whether its `cpu` or `cuda`. So, that specific line becomes `device= torch.device(0)` or `device= torch.device(1)`.

**Comment by beizhengren** [comment]
@sainatarajan Thank you. It worked for me ^ ^
