### ISSUE TITLE
ImportError: No module named 'utils

### ISSUE THREAD

**Issue by casiahnu** [Tramac/awesome-semantic-segmentation-pytorch#7]
hello, I run it on pytorch1.0.1 python3.5, but it has some problem with import models. when I run python ade20k.py --download-dir ./datasets/ade, I got "ImportError: No module named 'utils'"
How should I solve it? Thank you.

**Comment by Tramac** [comment]
Hi, if you run this scrip on the terminal directly, please add code before `from utils import download, makedirs`:
```
import sys
cur_path = os.path.abspath(os.path.dirname(__file__))
root_path = os.path.split(cur_path)[0]
sys.path.append(root_path)
```
Or you can run this script in the IDE (for example PyCharm) directly without adding anything.

**Comment by casiahnu** [comment]
thanks for your solution. When I run "python eval.py --model fcn32s --backbone vgg16 --dataset pascal_voc" on the terminal, I got "error argument --model invalid choice: 'fcn32s'(choose from fcn32s/fcn16s/fan8s/fan/psp/deeplabv3/danet/denseaspp/bisnet) ". I have no idea about that. What should I do? Thank you

**Comment by Tramac** [comment]
Hi, please change code `choices=["fcn32s/fcn16s/fan8s/fan/psp/deeplabv3/danet/denseaspp/bisnet"]` to `choices=["fcn32s", "fcn16s", "fcn8s", "psp", "deeplabv3", "danet", "denseaspp", "bisenet", "encnet", "dunet", "icnet"]`.
This bug has been fixed in new version, please see [there](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/0fc6686f8ab4d77e5cb77d8ca53f1de8cedb35ff/scripts/train.py#L24-L37).

**Comment by zhiyuli3** [comment]
Hi. I want to run the train.py, but in /core/nn/sync_bn/functions.py, line15, can't import lib, How can I fix it?
Thank you.

**Comment by Tramac** [comment]
Hi，please try to change “from core.nn.sync_bn import lib” to “from . import lib”.

**Comment by zhiyuli3** [comment]
> Hi，please try to change `from core.nn.sync_bn import lib` to `from . import lib`
Thank you su much, it's working now, And I find a type mistake in train.py, dataset argument,between 'ade20k', and 'citys' should have a ','.

**Comment by Tramac** [comment]
Thank you very much! I will fix it as soon as possible.
