### ISSUE TITLE
ImportError: /awesome-semantic-segmentation-pytorch-master/core/nn/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by ZijunYu** [Tramac/awesome-semantic-segmentation-pytorch#76]
I get this error when running train.py
python==3.6.9
torch==1.1.0
torchvision=0.3.0
cuda==9.0

**Comment by Tramac** [comment]
Hi, is [this](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/issues/24) helpful?

**Comment by ZijunYu** [comment]
That works for me! Thank you!

**Comment by Minghy** [comment]
Hi, can you tell me how you solved this problem?

**Comment by ZijunYu** [comment]
rm -r build, then recompile.

**Comment by scc-max** [comment]
how to recompile?

**Comment by wangliangwu** [comment]
recompile 
step1 remove -r build
step2 into the mmdetection dir the 
pip install -v -e . 
i think is it

**Comment by wangliangwu** [comment]
i solve it by upstairs  [hanbingmew]
step 1 
enter to the mmdetection dir 
the run the command     
remove -rf build
step2 
pip install -v -e.
the finnally the problem is sovled 
i feel very happy
