### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 82018303kazuma** [Tramac/Awesome-semantic-segmentation-pytorch#8]
It has been confirmed that the learning is well done at 99% to 100% even in the alternative estimation.
Performance is also the same as Caffe and Tensorflow.
Then I want to know why it didn't work before.
What did you improve?

**Comment by Tramac** [comment]
Hi, in the [alternative estimation](https://github.com/Tramac/Awesome-semantic-segmentation-pytorch/blob/master/tests), there is no data augmentation (rescale, random crop..) for the single test image. 
In the previous test, We forgot to change [mode](https://github.com/Tramac/Awesome-semantic-segmentation-pytorch/blob/149497f9cb54a1f650d8aff4088c540665ae381e/scripts/train.py#L114) to `testval`, which controls the data augmentation operation in [dataloader](https://github.com/Tramac/Awesome-semantic-segmentation-pytorch/blob/149497f9cb54a1f650d8aff4088c540665ae381e/core/data/dataloader/segbase.py#L46-L75).

**Comment by 82018303kazuma** [comment]
Hi Thank you for your reply

**Comment by Tramac** [comment]
Thank you for your participation. 
Is there any further testing? Has the mIoU improved?

**Comment by 82018303kazuma** [comment]
Performance is improved by the optimization algorithm.
Improvements were also seen with Augmentation(random Erase).
I feel that the performance was bad even with overfitting last time. Since it has been improved this time, I will try to improve the performance from now on.

**Comment by Tramac** [comment]
Thank you for your job!
Now the code already supports  saving the best model, you can change `fcn32s_%s_%s % (backbone, acronyms[dataset])` to `fcn32s_%s_%s_best_model % (backbone, acronyms[dataset])` in [there](https://github.com/Tramac/Awesome-semantic-segmentation-pytorch/blob/149497f9cb54a1f650d8aff4088c540665ae381e/core/models/fcn.py#L156)( for FCN32s). It This may improve performance.

**Comment by 82018303kazuma** [comment]
I feel that the training itself was not done well last time.
In the framework Pytorch was just too low, but the code has been improved and is almost equivalent.

Thank you for the meaningful code.
