### ISSUE TITLE
 No module named 'core'

### ISSUE THREAD

**Issue by wpffs** [Tramac/awesome-semantic-segmentation-pytorch#9]
Thx for your work！but  I have a problem that when I run demo.py, it retrun that "from core.utils.visualize import get_color_pallete
ModuleNotFoundError: No module named 'core'"
I have no idea about this. Could u fix it?
and when I run train.py, it's OK.

**Comment by Tramac** [comment]
Hi，please add code in demo.py:
cur_path = os.path.abspath(os.path.dirname(__file__))
root_path = os.path.split(cur_path)[0]
sys.path.append(root_path)

**Comment by wpffs** [comment]
Thank u so much! 
I also have another question that I need to split pedestrians from a picture. I have tried the model denseaspp121 and the results are ok. I want to know which model is better? could you give some suggestions.

**Comment by Tramac** [comment]
DenseASPP is a competitive method, maybe you can try deeplabv3 and DANet.
If you want to get fine edge, deeplabv3+ is a good choice, but it has not been implemented in these project, I will add it as soon as possible. Thank you for your participation!

**Comment by wpffs** [comment]
Thanks for your reply. I will try and follow your project.

**Comment by Tramac** [comment]
Thank you! I will keep updating and optimizing.

**Comment by HITjialanyu** [comment]
@Tramac sorry,after your adding code in citiscape.py,when "python cityscapes.py",the problem  also exists.

**Comment by Tramac** [comment]
Hi, please post the bug information.

**Comment by HITjialanyu** [comment]
![kk_image](https://user-images.githubusercontent.com/44438364/56779084-e9ec0980-680b-11e9-8299-df28041df0a6.png)
@Tramac ,sorry,there is  a limit for capture a screenshot

**Comment by Tramac** [comment]
Hi, it seems difficult to solve this bug, I will solve it as soon as possible.
Note: the cityscapes dataset cannot be downloaded through this script actually, because it requires you to register to log in [here](https://www.cityscapes-dataset.com/login/). Please download cityscapes dataset manually.
I'm sorry for this bug.

**Comment by HITjialanyu** [comment]
@Tramac  haha no matter, got it,Thank you for your help.And Thank you for your project.

**Comment by HITjialanyu** [comment]
@Tramac one more question,is only "cityscape"  your bisenet model dataset Support for?what if "VOC" "COCO" and "own dataset" for bisenet dataset? how about data format？

**Comment by Tramac** [comment]
All models support VOC, COCO, ADE20K and citys. Please change parameter `--datasets` in `train.py`.
If you want to run `demo.py`, Just add code like [this](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/28275b46f711d1ddf7b2df371e73085f588630be/core/models/fcn.py#L194) in [`bisenet`](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/28275b46f711d1ddf7b2df371e73085f588630be/core/models/bisenet.py#L223), then add the new function into [`model_zoo`](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/28275b46f711d1ddf7b2df371e73085f588630be/core/models/model_zoo.py#L56).

**Comment by HITjialanyu** [comment]
Thanks

**Comment by Tramac** [comment]
@HITjialanyu 
Hi, the bug has been fixed.
