### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'jpu'

### ISSUE THREAD

**Issue by lr1234567** [Tramac/awesome-semantic-segmentation-pytorch#97]
Traceback (most recent call last):
  File "train.py", line 339, in <module>
    trainer = Trainer(args)
  File "train.py", line 166, in __init__
    aux=args.aux, jpu=args.jpu, norm_layer=BatchNorm2d).to(self.device)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_zoo.py", line 137, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 131, in get_deeplabv3_plus
    model = DeepLabV3Plus(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 39, in __init__
    self.pretrained = get_xception(pretrained=pretrained_base, output_stride=output_stride, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/base_models/xception.py", line 387, in get_xception
    model = Xception65(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'jpu'
how to solve this problem?

**Comment by HaoweiGis** [comment]
你好，这个问题解决了吗，我也出现这个情况

**Comment by cspearl** [comment]
How did you solve this problem? I am having the same error

**Comment by liangliang98** [comment]
How did you solve this problem? I am having the same error

**Comment by littlecay** [comment]
same error， how do you solve it?

**Comment by liangliang98** [comment]
您好，您的来信已收到

**Comment by VictorYLA** [comment]
same error， how do you solve it?

**Comment by liangliang98** [comment]
您好，您的来信已收到

**Comment by 1maomaod** [comment]
> How did you solve this problem? I am having the same error

you solve this problem？

**Comment by liangliang98** [comment]
您好，您的来信已收到

**Comment by 1maomaod** [comment]
> same error， how do you solve it?
Have you solved it?

**Comment by 1maomaod** [comment]
> Traceback (most recent call last): File "train.py", line 339, in trainer = Trainer(args) File "train.py", line 166, in **init** aux=args.aux, jpu=args.jpu, norm_layer=BatchNorm2d).to(self.device) File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_zoo.py", line 137, in get_segmentation_model return models[model](**kwargs) File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 131, in get_deeplabv3_plus model = DeepLabV3Plus(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs) File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 39, in **init** self.pretrained = get_xception(pretrained=pretrained_base, output_stride=output_stride, **kwargs) File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/base_models/xception.py", line 387, in get_xception model = Xception65(**kwargs) TypeError: **init**() got an unexpected keyword argument 'jpu' how to solve this problem?

Have you solved it?
